name: docker image CI for ghcr

on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: build and push the image
        run: |
              echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin
              for tag in base qt5; do
                docker build . --build-arg DOCKER_TAG=${tag} --tag ${{ env.IMAGE_NAME }}:${tag}
                docker push ${{ env.IMAGE_NAME }}:${tag}
              done
              docker tag ${{ env.IMAGE_NAME }}:qt5 ${{ env.IMAGE_NAME }}:latest
              docker push ${{ env.IMAGE_NAME }}:latest
